<div class="field">
    <label for="billing:altura" class="required">
        <?php echo $this->__('Altura') ?>
    </label>
    <div class="input-box">
        <input type="text" name="billing[altura]" id="billing:altura" value="<?php echo $this->escapeHtml($this->getAddress()->getAltura()) ?>" title="<?php echo $this->__('Altura') ?>" class="input-text required-entry validate-number" />
    </div>
</div>
<div class="field">
    <label for="billing:observaciones">
        <?php echo $this->__('Observaciones') ?>
    </label>
    <div class="input-box">
        <input type="text" name="billing[observaciones]" id="billing:observaciones" value="<?php echo $this->escapeHtml($this->getAddress()->getObservaciones()) ?>" title="<?php echo $this->__('Observaciones') ?>" class="input-text" />
    </div>
</div>